language: node_js
node_js:
  - 10
before_script:
  - npm install @neuralegion/nexploit-cli -g || true
script:
  - printf "NEXPLOIT_TOKEN=$NEXPLOIT_TOKEN\nREPEATER=$REPEATER\n" > .env
  - cat .env
  - docker-compose --env-file=.env up -d
  - docker-compose config
  - printf "Start Nexploit Scan 🏁"
  - >
   SCAN_ID=$(nexploit-cli scan:run 
   --token $NEXPLOIT_TOKEN
   --repeater $REPEATER
   --name "Test Travis Scan"
   --crawler http://juiceshop.local:3000
   --smart)
  - echo $SCAN_ID
  - printf "Scan was started with ID https://nexploit.app/scans/$SCAN_ID\n"
  - printf "Wait for issues ⏳\n"
  - >
    (nexploit-cli scan:polling
    --interval 30s
    --timeout 20m
    --token $NEXPLOIT_TOKEN
    --breakpoint medium_issue $SCAN_ID)
allow_failure: true
after_script:
  - printf "Stop Scan 🛑" 
  - nexploit-cli scan:stop --token $NEXPLOIT_TOKEN $SCAN_ID

